Random split functionalities
vrtex-team/pytorch_geometric pull request #72
Opened 2021-07-14 08:46 UTC by RexYing

2021-07-14 08:55 UTC, RexYing commented
There are a few things that are flexible / can be adjusted:

1. Currently RandomLinkSplit returns 3 Data objects instead of 1 (for train / val / test)

2. Assumes that there could be multiple edge-related tensors for data. e.g. user can use "edge_attr", "edge_feature", "edge_weights" etc.  As long as the tensor name includes "edge_", it will be considered edge data and will be split.

3. Assumes that data.y has to be edge-related label if the user uses link split. (In deepsnap it's named as edge_label). It should usually be the case, unless there is some multi-task training.

4. The negative sampling is separate from link split (as another transform). still needs testing.

5. The tensor data.edge_label_index is created to denote the edge_index for edges used as objective in training / evaluation. E.g. in validation data object, the edge_label_index is the edge_index for validation edges.  In previous "train_test_split_edges" functionality, this is named as data.val_pos_edge_index. But since every split is its own data object here, we unify the naming of val_pos_edge_index and test_pos_edge_index.

6. It is also possible to have the training objective edges to be distinct from the set of training edges (in contrast to autoencoder). So we can have "train_pos_edge_index", which will be named as data_train.edge_label_index

2021-07-16 14:03 UTC, rusty1s commented
Thanks @RexYing, this looks pretty good already. Can we write a test to confirm that it's working as intended? With this, we can probably merge pretty soon.

2021-07-27 04:54 UTC, yaoyaowd commented on torch_geometric/transforms/random_link_split.py
> +    Check whether an attribute is a edge attribute.
is `an` edge attriubute

2021-07-27 04:54 UTC, yaoyaowd commented on torch_geometric/transforms/random_link_split.py
> +    return "edge" in key and "index" not in key
Why not directly use `key != 'edge_index'`? Also I think it is not good to assume feature is edge_feature, since default feature name is x.

2021-07-27 04:54 UTC, yaoyaowd commented on torch_geometric/transforms/random_link_split.py
> +            num_edges = data.num_edges // 2
I think we can infer `num_edges` from `data.edge_index` directly and it is universal for directed and undirected graph.

2021-07-27 04:54 UTC, yaoyaowd commented on torch_geometric/transforms/random_link_split.py
> +        if self.num_splits == 3:
is `self.num_splits == 3` the same as `num_test > 0`?

2021-07-27 04:54 UTC, yaoyaowd commented on torch_geometric/transforms/random_link_split.py
> +            test_edge_label_index = torch.index_select(data.edge_index, 1, edges_test)
also create label link for test?

2021-07-27 04:56 UTC, yaoyaowd commented on torch_geometric/transforms/random_link_split.py
> +        num_val: Union[int, float] = 0.1,
nit, num_val and num_test should be pct_val and pct_test?

2021-07-28 11:52 UTC, rusty1s requested changes

2021-07-28 11:52 UTC, rusty1s commented on torch_geometric/transforms/random_link_split.py
> +        num_splits (int, optional): The number of splits to add.
I think this argument is unnecessary. If someone does not want a validation split, the user can simple pass in `num_val=0`. WDYT?

2021-07-28 11:52 UTC, rusty1s commented on torch_geometric/transforms/random_link_split.py
> +            num_edges = data.num_edges // 2
We still need to have different functionality for undirected/directed graphs for link-level splits, so I think the code is correct. Instead of calling `data.is_undirected` (which is an expensive op), we can also set this as an argument.

2021-07-28 11:52 UTC, rusty1s commented on torch_geometric/transforms/random_link_split.py
> +        print(num_edges)
remove

2021-07-28 11:52 UTC, rusty1s commented on torch_geometric/transforms/random_link_split.py
> +            data_val = copy.copy(data_train)
we probably should copy data for each split, i.e., also copy for `data_train`.

2021-07-28 11:52 UTC, rusty1s commented on torch_geometric/transforms/random_link_split.py
> +        train_edge_label_index = torch.index_select(data.edge_index, 1, edges_train)
Any reason you use `index_select` directly? Isn't `edge_index[:, edges_train]` more convenient to read?

2021-07-28 11:52 UTC, rusty1s commented on torch_geometric/transforms/random_link_split.py
> +        # this assumes that the second half of edges are the reverse direction
I think this does not have to be the case. A safer way is to mask `edge_index` first via `edge_index[0] < edge_index[1]`.

2021-07-29 06:24 UTC, JiaxuanYou commented on torch_geometric/transforms/random_link_split.py
> +    return "edge" in key and "index" not in key
The naming convention of PyG seems to be `edge_attr`.
By the way, my understanding is `x` is only used for node features in PyG.

2021-07-29 06:29 UTC, JiaxuanYou commented on torch_geometric/transforms/random_link_split.py
> +            return [data_train, data_val, data_test]
We may want to support returning 1 data object as well. We could add an argument to control the `return` behavior

2021-07-29 06:35 UTC, JiaxuanYou commented on examples/split_examples.py
> +    *[link_split_transform(data) for data in dataset])
Does this work when a dataset have multiple graphs?
In that case `dataset_train` will be a list of graph, instead of being a PyG dataset object.

2021-07-29 06:35 UTC, JiaxuanYou commented on torch_geometric/transforms/random_link_split.py
> +                if data.is_undirected():
Is this an expected behavior?
Here we duplicate the `edge_feature`, however the data is still `undirected`. Will this operation double edge_feature all the times?

2021-07-29 06:35 UTC, JiaxuanYou commented on torch_geometric/transforms/random_link_split.py
> +
We may want to support returning 1 data object as well. We could add an argument to control the `return` behavior

2021-07-29 06:35 UTC, JiaxuanYou commented on torch_geometric/transforms/random_link_split.py
> +            method="sparse", force_undirected=False)
`force_undirected` should be an input argument that user can control

2021-07-29 08:50 UTC, RexYing commented on torch_geometric/transforms/random_link_split.py
> +    return "edge" in key and "index" not in key
the check is for 'edge_anything' to be considered as edge attributes to be copied. Is that a reasonable assumption?

2021-07-29 08:52 UTC, RexYing commented on torch_geometric/transforms/random_link_split.py
> +        if self.num_splits == 3:
Yes. I also assume here that the user might not specify num_test, and only use (num_splits=3, num_train=x, num_val=y), as long as x+y < 1.

2021-07-29 12:33 UTC, rusty1s commented on torch_geometric/transforms/random_link_split.py
> +    return "edge" in key and "index" not in key
That's reasonable IMO. In contrast to `HeteroData`, the `Data` object does not differentiate between node and edge features, so we need to make some assumptions. Another one is to check the shapes of tensors (which we usually do in PyG), *e.g.*, see [here](https://github.com/vrtex-team/pytorch_geometric/blob/master/torch_geometric/data/cluster.py#L89-L93).

2021-07-29 12:40 UTC, rusty1s commented on examples/split_examples.py
> +    *[link_split_transform(data) for data in dataset])
I think this is not a problem for now, as a PyG dataset is literally a list of data objects and works as input to `DataLoader` as well.

2021-07-29 12:40 UTC, rusty1s commented on torch_geometric/transforms/random_link_split.py
> +
+1

2021-08-02 22:59 UTC, RexYing commented on torch_geometric/transforms/random_link_split.py
> +    Check whether an attribute is a edge attribute.
thx

2021-08-02 22:59 UTC, RexYing commented on torch_geometric/transforms/random_link_split.py
> +            num_edges = data.num_edges // 2
thx. set an argument

2021-08-02 23:05 UTC, RexYing commented on torch_geometric/transforms/random_link_split.py
> +        if self.num_splits == 3:
Yes. Maybe I will just use num_test > 0 and omit the num_splits argument

2021-08-02 23:17 UTC, RexYing commented on torch_geometric/transforms/random_link_split.py
> +            test_edge_label_index = torch.index_select(data.edge_index, 1, edges_test)
yes. label for link prediction is created for all splits

2021-08-02 23:18 UTC, RexYing commented on torch_geometric/transforms/random_link_split.py
> +        num_val: Union[int, float] = 0.1,
I'll be testing both cases when the num_val is specified as percentage and absolute number of edges

if isinstance(self.num_val, float):
        num_edges_val = int(self.num_val * num_edges)
else:
        num_edges_val = self.num_val

2021-08-02 23:20 UTC, RexYing commented on torch_geometric/transforms/random_link_split.py
> +            data_val = copy.copy(data_train)
For data_train, it is copied in _create_split_data function

2021-08-03 00:10 UTC, RexYing commented on torch_geometric/transforms/random_link_split.py
> +        train_edge_label_index = torch.index_select(data.edge_index, 1, edges_train)
changed to slicing throughout

2021-08-03 03:59 UTC, JiaxuanYou commented on examples/split_examples.py
> +    *[link_split_transform(data) for data in dataset])
@rusty1s I have a question here. I found that in most PyG native dataset, collated data tensors are stored. Therefore the behavior is somewhat different from a list of data objects?

2021-08-03 05:33 UTC, rusty1s commented on examples/split_examples.py
> +    *[link_split_transform(data) for data in dataset])
The storage is indeed different, but the functionality is equivalent (slicing, iterating, …). As such, there is no real difference between datasets and lists of data from a user perspective.

2021-08-10 08:11 UTC, rusty1s requested changes
Thanks @RexYing for adding in the tests. This looks quite good already. I run `flake8` on your changes so that linting tests should now succeed. Please see my feedback in the code comments so that we can quickly merge.

2021-08-10 08:11 UTC, rusty1s commented on torch_geometric/transforms/random_link_split.py
> +                    data, torch.cat([edges_train, edges_val]))
`edges[:num_edges_train + num_edges_val]` should be more efficient.

2021-08-10 08:11 UTC, rusty1s commented on torch_geometric/transforms/random_link_split.py
> +            if self.num_val != 0:
Where does `data_val` gets created? Furthermore, I don't think the `copy.copy` is needed here as `_create_split_data` already copies the data.

2021-08-10 08:11 UTC, rusty1s commented on torch_geometric/transforms/random_link_split.py
> +                edge_index tensor.
`key` docstring missing

2021-08-10 08:11 UTC, rusty1s commented on torch_geometric/transforms/random_link_split.py
> +        train_edge_label_index = data.edge_index[:, edges_train]
`train_edge_label_index == edges_train`, right? I think you are interested in the indices of training edges, rather than its `[2, num_train_edges]` representation.

2021-08-10 08:11 UTC, rusty1s commented on torch_geometric/transforms/random_link_split.py
> +    def _create_negative_samples(self, data, neg_sampling_ratio=1.0, key=None):
Shall we add `neg_sampling_ratio` to `__init__` as well?

2021-08-10 19:37 UTC, RexYing commented on torch_geometric/transforms/random_link_split.py
> +        if is_undirected is None:
The None option is just for convenience if user does not want to specify. We could still determine with data.is_undirected() call, if user specifies None?

2021-08-10 19:48 UTC, rusty1s commented on torch_geometric/transforms/random_link_split.py
> +        if is_undirected is None:
Ah, I see. Makes sense. Then `is_undirected` should be of type `Optional[bool]`.

2021-08-10 20:41 UTC, RexYing commented on torch_geometric/transforms/random_link_split.py
> +        if self.is_undirected:
with edge_index = edge_index[:, edge_index[0] <= edge_index[1]] should work for self-loops?

2021-08-10 20:45 UTC, RexYing commented on torch_geometric/transforms/random_link_split.py
> +            if self.num_val != 0:
data_val is just a copy of data_train, since their difference is only on their edge label and edge_index for edge label (edge_label_index). These will be modified later in "_create_label_link_pred". So here I just need to copy data_train as data_val, without calling “_create_split_data” for data_val.

2021-08-10 20:52 UTC, RexYing commented on torch_geometric/transforms/random_link_split.py
> +        train_edge_label_index = data.edge_index[:, edges_train]
In "_create_label_link_pred", I directly assign this train_edge_label_index into the train_data.edge_label_index. It will be [2, num_train_edges], so that the user can compute the link pred scores, 
e.g. torch.sum( embedding[data.edge_label_index[0]] *embedding[data.edge_label_index[1]], dim=1)

2021-08-11 06:18 UTC, rusty1s commented on torch_geometric/transforms/random_link_split.py
> +        if self.is_undirected:
Yes, you are right :)

2021-08-11 06:22 UTC, rusty1s commented on torch_geometric/transforms/random_link_split.py
> +        train_edge_label_index = data.edge_index[:, edges_train]
Yes, that makes sense. However, in `create_label_link_pred`, you are using this tensor to index the edge label, which results in undefined behaviour: `edge_label = data.edge_label[edges]`

2021-08-12 09:49 UTC, merged